/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FairGradeForgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assignments"
      | "createAssignment"
      | "getAssignment"
      | "getGrade"
      | "getSubmission"
      | "gradeSubmission"
      | "grades"
      | "hasGrade"
      | "hasSubmitted"
      | "protocolId"
      | "startGrading"
      | "submissions"
      | "submitAssignment"
      | "teacher"
      | "totalAssignments"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssignmentCreated"
      | "GradeAssigned"
      | "SubmissionCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assignments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAssignment",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssignment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGrade",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmission",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gradeSubmission",
    values: [BigNumberish, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grades",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasGrade",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startGrading",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submissions",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitAssignment",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "teacher", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalAssignments",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "assignments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAssignment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssignment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gradeSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grades", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasGrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startGrading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAssignment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "teacher", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAssignments",
    data: BytesLike
  ): Result;
}

export namespace AssignmentCreatedEvent {
  export type InputTuple = [
    assignmentId: BigNumberish,
    teacher: AddressLike,
    title: string,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    assignmentId: bigint,
    teacher: string,
    title: string,
    deadline: bigint
  ];
  export interface OutputObject {
    assignmentId: bigint;
    teacher: string;
    title: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GradeAssignedEvent {
  export type InputTuple = [
    assignmentId: BigNumberish,
    student: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    assignmentId: bigint,
    student: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    assignmentId: bigint;
    student: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionCreatedEvent {
  export type InputTuple = [
    assignmentId: BigNumberish,
    student: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    assignmentId: bigint,
    student: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    assignmentId: bigint;
    student: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FairGradeForge extends BaseContract {
  connect(runner?: ContractRunner | null): FairGradeForge;
  waitForDeployment(): Promise<this>;

  interface: FairGradeForgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assignments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, bigint, boolean] & {
        id: bigint;
        title: string;
        requirements: string;
        deadline: bigint;
        teacher: string;
        submissionCount: bigint;
        isGrading: boolean;
      }
    ],
    "view"
  >;

  createAssignment: TypedContractMethod<
    [title: string, requirements: string, deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getAssignment: TypedContractMethod<
    [assignmentId: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        title: string;
        requirements: string;
        deadline: bigint;
        submissionCount: bigint;
        isGrading: boolean;
      }
    ],
    "view"
  >;

  getGrade: TypedContractMethod<
    [assignmentId: BigNumberish, student: AddressLike],
    [
      [string, bigint, boolean] & {
        encryptedScore: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getSubmission: TypedContractMethod<
    [assignmentId: BigNumberish, student: AddressLike],
    [
      [string, bigint, boolean] & {
        encryptedAnswer: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  gradeSubmission: TypedContractMethod<
    [
      assignmentId: BigNumberish,
      student: AddressLike,
      encryptedScore: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  grades: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, boolean] & {
        encryptedScore: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  hasGrade: TypedContractMethod<
    [assignmentId: BigNumberish, student: AddressLike],
    [boolean],
    "view"
  >;

  hasSubmitted: TypedContractMethod<
    [assignmentId: BigNumberish, student: AddressLike],
    [boolean],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  startGrading: TypedContractMethod<
    [assignmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submissions: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, string, bigint, boolean] & {
        student: string;
        encryptedAnswer: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  submitAssignment: TypedContractMethod<
    [
      assignmentId: BigNumberish,
      encryptedAnswer: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  teacher: TypedContractMethod<[], [string], "view">;

  totalAssignments: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assignments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, bigint, boolean] & {
        id: bigint;
        title: string;
        requirements: string;
        deadline: bigint;
        teacher: string;
        submissionCount: bigint;
        isGrading: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAssignment"
  ): TypedContractMethod<
    [title: string, requirements: string, deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAssignment"
  ): TypedContractMethod<
    [assignmentId: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        title: string;
        requirements: string;
        deadline: bigint;
        submissionCount: bigint;
        isGrading: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGrade"
  ): TypedContractMethod<
    [assignmentId: BigNumberish, student: AddressLike],
    [
      [string, bigint, boolean] & {
        encryptedScore: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubmission"
  ): TypedContractMethod<
    [assignmentId: BigNumberish, student: AddressLike],
    [
      [string, bigint, boolean] & {
        encryptedAnswer: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "gradeSubmission"
  ): TypedContractMethod<
    [
      assignmentId: BigNumberish,
      student: AddressLike,
      encryptedScore: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grades"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, boolean] & {
        encryptedScore: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasGrade"
  ): TypedContractMethod<
    [assignmentId: BigNumberish, student: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<
    [assignmentId: BigNumberish, student: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "startGrading"
  ): TypedContractMethod<[assignmentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submissions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, string, bigint, boolean] & {
        student: string;
        encryptedAnswer: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitAssignment"
  ): TypedContractMethod<
    [
      assignmentId: BigNumberish,
      encryptedAnswer: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "teacher"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalAssignments"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AssignmentCreated"
  ): TypedContractEvent<
    AssignmentCreatedEvent.InputTuple,
    AssignmentCreatedEvent.OutputTuple,
    AssignmentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GradeAssigned"
  ): TypedContractEvent<
    GradeAssignedEvent.InputTuple,
    GradeAssignedEvent.OutputTuple,
    GradeAssignedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionCreated"
  ): TypedContractEvent<
    SubmissionCreatedEvent.InputTuple,
    SubmissionCreatedEvent.OutputTuple,
    SubmissionCreatedEvent.OutputObject
  >;

  filters: {
    "AssignmentCreated(uint256,address,string,uint256)": TypedContractEvent<
      AssignmentCreatedEvent.InputTuple,
      AssignmentCreatedEvent.OutputTuple,
      AssignmentCreatedEvent.OutputObject
    >;
    AssignmentCreated: TypedContractEvent<
      AssignmentCreatedEvent.InputTuple,
      AssignmentCreatedEvent.OutputTuple,
      AssignmentCreatedEvent.OutputObject
    >;

    "GradeAssigned(uint256,address,uint256)": TypedContractEvent<
      GradeAssignedEvent.InputTuple,
      GradeAssignedEvent.OutputTuple,
      GradeAssignedEvent.OutputObject
    >;
    GradeAssigned: TypedContractEvent<
      GradeAssignedEvent.InputTuple,
      GradeAssignedEvent.OutputTuple,
      GradeAssignedEvent.OutputObject
    >;

    "SubmissionCreated(uint256,address,uint256)": TypedContractEvent<
      SubmissionCreatedEvent.InputTuple,
      SubmissionCreatedEvent.OutputTuple,
      SubmissionCreatedEvent.OutputObject
    >;
    SubmissionCreated: TypedContractEvent<
      SubmissionCreatedEvent.InputTuple,
      SubmissionCreatedEvent.OutputTuple,
      SubmissionCreatedEvent.OutputObject
    >;
  };
}
